function [] = drawCircle(x,y,radius,fillColor,lineColor)
    % [left_x,bottom_y,width,height]
    pos = [x-radius,y-radius,radius*2,radius*2];
    rectangle('position',pos,...
              'curvature',[1,1],...
              'edgeColor',lineColor,...
              'FaceColor',fillColor,...
              'lineWidth',1);
end

