function [rect] = drawCircle(nodeIdx,radius)
    global nodes;
    % [left_x,bottom_y,width,height]
    pos = [nodes(nodeIdx).x-radius,nodes(nodeIdx).y-radius,radius*2,radius*2];
    rect = rectangle('position',pos,...
              'curvature',[1,1],...
              'edgeColor',nodes(nodeIdx).color,...
              'FaceColor','black',...
              'lineWidth',1);
end